name: 'umkmall_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'umkmall_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  umkmall_analytics:
    # Staging layer - light transformations
    staging:
      +materialized: view
      +schema: staging

    # Intermediate layer - unions and joins
    intermediate:
      +materialized: table
      +schema: intermediate

    # Mart layer - final business logic
    marts:
      +materialized: table
      +schema: marts

# Seeds configuration
seeds:
  umkmall_analytics:
    +schema: seeds

vars:
  # Set the timezone for all timestamp conversions
  timezone: 'UTC'
