version: 2

sources:
  - name: raw
    description: Raw data ingested from various sources
    database: "{{ env_var('POSTGRES_DB', 'analytics') }}"
    schema: raw
    tables:
      - name: purchase_form_data
        description: Customer purchase data from Supabase product database
        columns:
          - name: email
            description: Customer email address (normalized)
          - name: phone_number
            description: Customer phone number (normalized to +62 format)
          - name: data_source
            description: Source identifier

      - name: leads_ads_community
        description: Lead registration data from Ads Community Google Sheets
        columns:
          - name: email
            description: Lead email address (normalized)
          - name: phone_number
            description: Lead phone number (normalized)
          - name: sheet_name
            description: Original sheet name in the spreadsheet
          - name: data_source
            description: Source identifier

      - name: website_form_responses
        description: Lead registration data from Website Form Google Sheets
        columns:
          - name: email
            description: Lead email address (normalized)
          - name: phone_number
            description: Lead phone number (normalized)
          - name: sheet_name
            description: Original sheet name in the spreadsheet
          - name: data_source
            description: Source identifier

      - name: leads_course_strategi_ads
        description: Lead registration data from Course Strategy Ads Google Sheets
        columns:
          - name: email
            description: Lead email address (normalized)
          - name: phone_number
            description: Lead phone number (normalized)
          - name: sheet_name
            description: Original sheet name in the spreadsheet
          - name: data_source
            description: Source identifier

      - name: branding_level_up
        description: Lead registration data from Branding Level Up Google Sheets
        columns:
          - name: email
            description: Lead email address (normalized)
          - name: phone_number
            description: Lead phone number (normalized)
          - name: sheet_name
            description: Original sheet name in the spreadsheet
          - name: data_source
            description: Source identifier

      - name: eduqat_enrollments
        description: Course enrollment data from Eduqat API
        columns:
          - name: id
            description: Unique enrollment identifier
          - name: user_id
            description: User identifier
          - name: course_id
            description: Course identifier
          - name: user_data
            description: JSONB containing user information (name, email, phone, etc.)
          - name: metadata
            description: JSONB containing enrollment metadata including started_at, tracked_time
          - name: completions
            description: JSONB containing material completion data
          - name: certificates
            description: JSONB array of earned certificates
          - name: learning_progress
            description: Progress percentage (0-100)
          - name: learning_time
            description: Total learning time in seconds
          - name: data_source
            description: Source identifier
