version: 2

sources:
  - name: raw
    description: Raw data ingested from various sources
    database: "{{ env_var('POSTGRES_DB', 'analytics') }}"
    schema: raw
    tables:
      - name: purchase_form_data
        description: Customer purchase data from Supabase product database
        columns:
          - name: customer_name
            description: Customer full name
          - name: email
            description: Customer email address (normalized)
          - name: phone_number
            description: Customer phone number (normalized to +62 format)
          - name: data_source
            description: Source identifier

      - name: leads_ads_community
        description: Lead registration data from Ads Community Google Sheets
        columns:
          - name: email
            description: Lead email address (normalized)
          - name: phone_number
            description: Lead phone number (normalized)
          - name: sheet_name
            description: Original sheet name in the spreadsheet
          - name: data_source
            description: Source identifier

      - name: website_form_responses
        description: Lead registration data from Website Form Google Sheets
        columns:
          - name: email
            description: Lead email address (normalized)
          - name: phone_number
            description: Lead phone number (normalized)
          - name: sheet_name
            description: Original sheet name in the spreadsheet
          - name: data_source
            description: Source identifier

      - name: leads_course_strategi_ads
        description: Lead registration data from Course Strategy Ads Google Sheets
        columns:
          - name: email
            description: Lead email address (normalized)
          - name: phone_number
            description: Lead phone number (normalized)
          - name: sheet_name
            description: Original sheet name in the spreadsheet
          - name: data_source
            description: Source identifier

      - name: branding_level_up
        description: Lead registration data from Branding Level Up Google Sheets
        columns:
          - name: email
            description: Lead email address (normalized)
          - name: phone_number
            description: Lead phone number (normalized)
          - name: sheet_name
            description: Original sheet name in the spreadsheet
          - name: data_source
            description: Source identifier

      - name: eduqat_enrollments
        description: Course enrollment data from Eduqat API
        columns:
          - name: id
            description: Unique enrollment identifier
          - name: user_id
            description: User identifier
          - name: course_id
            description: Course identifier
          - name: user_data
            description: JSONB containing user information (name, email, phone, etc.)
          - name: metadata
            description: JSONB containing enrollment metadata including started_at, tracked_time
          - name: completions
            description: JSONB containing material completion data
          - name: certificates
            description: JSONB array of earned certificates
          - name: learning_progress
            description: Progress percentage (0-100)
          - name: learning_time
            description: Total learning time in seconds
          - name: data_source
            description: Source identifier

      - name: eduqat_users
        description: User data from Eduqat API
        columns:
          - name: id
            description: Unique user identifier (integer)
          - name: user_id
            description: User ID (same as id)
          - name: subid
            description: UUID identifier for the user
          - name: name
            description: User's display name
          - name: email
            description: User's email address
          - name: phone_number
            description: User's phone number
          - name: role
            description: User role (learner, admin, user)
          - name: status
            description: Account status (ACTIVE, CONFIRMED)
          - name: total_course
            description: Number of courses created by user
          - name: total_enrollment
            description: Number of course enrollments
          - name: created_at
            description: Account creation timestamp
          - name: data_source
            description: Source identifier

      - name: eduqat_courses
        description: Course data from Eduqat API
        columns:
          - name: id
            description: Unique course identifier
          - name: name
            description: Course name/title
          - name: slug
            description: URL-friendly course identifier
          - name: description
            description: Course description (JSON text blocks)
          - name: type
            description: Course type (self-learn, live, etc.)
          - name: status
            description: Course status (active, hidden, etc.)
          - name: duration
            description: Course duration in seconds
          - name: total_student
            description: Total number of enrolled students
          - name: rating
            description: Course rating
          - name: published_at
            description: Course publication timestamp
          - name: data_source
            description: Source identifier

      - name: eduqat_ai_conversations
        description: AI tutor conversation data from Eduqat API
        columns:
          - name: id
            description: Unique submission ID (integer)
          - name: conversation_id
            description: Unique conversation/session identifier
          - name: user_id
            description: UUID of the user
          - name: enrollment_id
            description: Links to the user's enrollment
          - name: course_id
            description: Course identifier
          - name: material_id
            description: Material/lesson identifier where conversation occurred
          - name: status
            description: Conversation status (WAITING, COMPLETED, etc.)
          - name: score
            description: Score if graded
          - name: user_data
            description: JSONB containing user information (name, email, etc.)
          - name: educator_data
            description: JSONB containing educator information
          - name: messages
            description: JSONB array of conversation messages with sender, value, timestamp
          - name: data_source
            description: Source identifier

      - name: eduqat_survey_results
        description: Survey results fetched from Eduqat API for completed surveys
        columns:
          - name: enrollment_id
            description: Enrollment ID (part of composite key)
          - name: material_id
            description: Material ID of the survey (part of composite key)
          - name: survey_id
            description: Unique survey identifier
          - name: course_id
            description: Course identifier
          - name: user_id
            description: User who completed the survey
          - name: survey_type
            description: Type of survey
          - name: survey_title
            description: Title of the survey
          - name: elements
            description: JSONB array of survey elements (questions with responses)
          - name: completed_at
            description: Timestamp when survey was completed
          - name: data_source
            description: Source identifier

      - name: ai_chat_messages
        description: AI chat messages from the product database
        columns:
          - name: id
            description: Unique message identifier (UUID)
          - name: session_id
            description: Chat session identifier (UUID)
          - name: role
            description: Message sender role (user, assistant, etc.)
          - name: content
            description: Message content text
          - name: message_order
            description: Order of message within the session
          - name: created_at
            description: Timestamp when message was created
          - name: data_source
            description: Source identifier

      - name: ai_chat_sessions
        description: AI chat sessions from the product database
        columns:
          - name: id
            description: Unique session identifier (UUID)
          - name: user_id
            description: User identifier (UUID)
          - name: guest_session_id
            description: Guest session identifier for unauthenticated users
          - name: title
            description: Session title
          - name: created_at
            description: Timestamp when session was created
          - name: updated_at
            description: Timestamp when session was last updated
          - name: data_source
            description: Source identifier
