version: 2

models:
  - name: int_all_marketing_leads
    description: Union of all marketing lead sources from Google Sheets
    columns:
      - name: email
        description: Normalized lead email
      - name: phone_number
        description: Normalized lead phone (+62 format)
      - name: nama_usaha
        description: Business name
      - name: nama_pemilik_usaha
        description: Business owner name
      - name: nama_akun_media_sosial
        description: Social media account name
      - name: nama_akun_ecommerce
        description: E-commerce account name
      - name: bidang_usaha
        description: Business sector/field
      - name: lama_usaha
        description: Business duration/age
      - name: provinsi_usaha
        description: Province of business
      - name: pendapatan_bulanan
        description: Monthly revenue
      - name: tergabung_komunitas_umkm
        description: Member of UMKM community
      - name: memiliki_nib
        description: Has NIB (business registration)
      - name: memiliki_sertifikasi_halal
        description: Has halal certification
      - name: timestamp
        description: Form submission timestamp
      - name: sheet_name
        description: Source Google Sheet name
      - name: data_source
        description: Source identifier
      - name: extracted_at
        description: Data extraction timestamp

  - name: int_ai_chat_messages
    description: AI chat messages joined with session data to include user information
    columns:
      - name: message_id
        description: Unique message identifier (UUID)
      - name: session_id
        description: Chat session identifier (UUID)
      - name: user_id
        description: User identifier (UUID) from the session
      - name: guest_session_id
        description: Guest session identifier for unauthenticated users
      - name: session_title
        description: Title of the chat session
      - name: role
        description: Message sender role (user, assistant, etc.)
      - name: content
        description: Message content text
      - name: message_order
        description: Order of message within the session
      - name: message_created_at
        description: Timestamp when message was created
      - name: session_created_at
        description: Timestamp when session was created
      - name: session_updated_at
        description: Timestamp when session was last updated